### ISSUE TITLE
layer snap invokes method `is_container` to determine squashfuse support

### ISSUE THREAD

**Issue by chuckbutler** [stub42/layer-snap#10]
Greetings Stub,

A [community member](https://askubuntu.com/questions/911996/errors-deploying-kubernetes-cluster-on-aws) appears to have deployed CDK but ran into a blocker that I have not encountered during our testing.

```
root@ip-10-35-0-44:/var/lib/juju/agents/unit-kubernetes-master-1/charm# ./hooks/cni-relation-changed
Traceback (most recent call last):
  File "./hooks/cni-relation-changed", line 19, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 77, in main
    hookenv._run_atstart()
  File "/usr/local/lib/python3.5/dist-packages/charmhelpers/core/hookenv.py", line 1000, in _run_atstart
    callback(*args, **kwargs)
  File "/var/lib/juju/agents/unit-kubernetes-master-1/charm/reactive/snap.py", line 81, in ensure_snapd
    if host.is_container() and not shutil.which('squashfuse'):
AttributeError: module 'charmhelpers.core.host' has no attribute 'is_container'
```

Do we know when this function was landed and if this is a byproduct of a failed sync during our latest publication? I've deployed both CDK and Kubernetes-Core to AWS and not encountered this issue.

Any help/guidance here is appreciated

**Comment by stub42** [comment]
On 11 May 2017 at 00:55, Charles Butler <notifications@github.com> wrote:

> Greetings Stub,
>
> A community member
> <https://askubuntu.com/questions/911996/errors-deploying-kubernetes-cluster-on-aws>
> appears to have deployed CDK but ran into a blocker that I have not
> encountered during our testing.
>
> root@ip-10-35-0-44:/var/lib/juju/agents/unit-kubernetes-master-1/charm# ./hooks/cni-relation-changed
> Traceback (most recent call last):
>   File "./hooks/cni-relation-changed", line 19, in <module>
>     main()
>   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 77, in main
>     hookenv._run_atstart()
>   File "/usr/local/lib/python3.5/dist-packages/charmhelpers/core/hookenv.py", line 1000, in _run_atstart
>     callback(*args, **kwargs)
>   File "/var/lib/juju/agents/unit-kubernetes-master-1/charm/reactive/snap.py", line 81, in ensure_snapd
>     if host.is_container() and not shutil.which('squashfuse'):
> AttributeError: module 'charmhelpers.core.host' has no attribute 'is_container'
>
> Do we know when this function was landed and if this is a byproduct of a
> failed sync during our latest publication? I've deployed both CDK and
> Kubernetes-Core to AWS and not encountered this issue.
>
> Any help/guidance here is appreciated
>

That particular method has been around since November last year (per bzr
blame at http://pastebin.ubuntu.com/24553340/)

The only thing I can think of would be that the host already had an old
version of charm-helpers installed and when the basic layer ran pip it
decided that version was good enough and didn't bother with the newer
version. You might be able to see this earlier in the juju logs, when
charms.reactive is bootstrapping itself. If you had managed to embed a very
old version in your charm, it would show up in testing. Or perhaps the
charm-helpers installation failed completely, and charmhelpers/core/host.py
is empty or some similar nonsense.

**Comment by stub42** [comment]
Closing this, as there is nothing for the snap layer to do. Any failure happened earlier, before the snap layer's handlers where run. It's charms.reactive's job to get charm-helpers installed correctly.

**Comment by chuckbutler** [comment]
Thanks for the investigative work. I've removed the comment linking here and invited the user to a more responsive debugging session on IRC as I have no clue how they got into that scenario.
