### ISSUE TITLE
Improve handling of resource path acquisition 

### ISSUE THREAD

**Issue by wwwtyro** [stub42/layer-snap#11]
`hookenv.resource_get` can sometimes return `None` even if there will be a nonzero resource available. This isn't handled [here](https://github.com/stub42/layer-snap/blob/master/lib/charms/layer/snap.py#L191).

I saw [this case](https://github.com/juju/juju/blob/develop/state/resources_persistence_staged.go#L32) triggered when multiple machines were coming online simultaneously that all needed the same snap resources from the charm store, resulting in [this error](https://gist.github.com/wwwtyro/053dfb7d8e25e011097ed8429bff6c19#file-gistfile1-txt-L665).

One solution might be to require at least zero-byte resources and only install from the snap store when the resource is zero bytes.

**Comment by stub42** [comment]
Is there a Juju bug open on this issue? The resource-get tool failing to get a resource seems a critical bug to fix. It has one job to do, and if we can't rely on it we can't rely on it.

I am loathe to require zero-byte resources in all cases. It increases the burden on developers further and would rather the Juju bug fixed. Most charms I'm seeing are avoiding using the resource feature due to this burden. I've been pushing for Juju to support optional resources as they are in practice the vastly most common use case, and requiring resources here would cement this poor developer experience in the snap layer. It doesn't seem a good trade of to work around a Juju bug.

**Comment by wwwtyro** [comment]
@stub42 Good points, & I think we might be able to address this better in the hookenv lib.
