### ISSUE TITLE
Automatically install squashfuse to support snaps in more places

### ISSUE THREAD

**Issue by chuckbutler** [stub42/layer-snap#5]
Snapd doesn't run well by itself in LXD, in order to support snaps in more places can layer-snap handle installing squashfuse during its own bootstrap phase to ensure the snaps will work when delivered to a LXD hosted model?

I think this may end up going away when the snapd package depends on squashfuse (assuming) but this is a valid workaround until then. I admittedly don't know the full implications of this, but it appears to work reliably on xenial+lxd combinations, which is the only place I've tested this.

Thoughts?

**Comment by stub42** [comment]
It sounds like a fantastic idea, which is why I landed it a few days ago ;)

https://github.com/stub42/layer-snap/commit/31e5acf9d40fab24e26131c930b657497a9e40d2

Its being added as a dependency to snapd, so I can pull the work around when that is in xenial-updates.

It doesn't help trusty lxd containers alas, as they are unable to support snaps.

**Comment by chuckbutler** [comment]
FAN Tastic! Thanks stub!
