### ISSUE TITLE
Support classic snaps in limited egress environments 

### ISSUE THREAD

**Issue by wwwtyro** [stub42/layer-snap#9]
If a user is deploying classic snaps in a limited egress environment and does not currently have the core snap installed, their installation will fail.

@stub42, might we add the core snap as a resource to layer-snap so that the user can provide it in these scenarios?

https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/256

**Comment by stub42** [comment]
I believe this would work. I think you could do it right now in your charm by adding the necessary declarations to layer.yaml and metadata.yaml and uploading the core snap as a resource.

I cannot pre-declare the resource in the snap layer, as that would break Juju 1.25 compatibility. Also, if I did this then everyone using the snap layer would be required to upload a 0 byte resource when they published their charm, no matter if they want this feature or not (this is https://github.com/juju/charmstore-client/issues/103 yet again).

What I can do in the snap layer is ensure that the 'core' snap is always installed first if it is declared. The charm author would still need to add the resource declaration in metadata.yaml, and upload a 0 byte resource as the core.snap at charm publication time.

All that said, a question is do we actually want to do this? Deployments done this way will not get automatic security updates, and thus snap deployments become *worse* than the equivalent using debs. This is because Juju deployments require access to an Ubuntu archive, which should be receiving updates, but snap updates would not happen until a fresh resource is uploaded and an 'upgrade-charm' run. The alternative is requiring access to a web proxy with access to the snap store as a minimum (the snap layer already supports this, but only under Xenial+). This may may some test and ephemeral deployments trickier, but blocks people attempting to do production deploys in a way that disables core features of snaps that we are trying to promote as advantages over traditional distribution. Do you really want to deal with the fallout from compromised Kubernetes deployments because the network restrictions designed to increase security silently stopped security updates working and actually making the deployment more vulnerable?

**Comment by chuckbutler** [comment]
I agree with you here stub. This is a terrible path for users to follow if they expect automatic security updates. We'll be resigning a lot of enterprise customers to forget to update their core snaps in some places and we will likely get the blame for their inaction.

There's got to be a better way to do this than offlining with resources.
